services:
  web:
    container_name: ifc-web-app
    image: cesosag/ifc-web
    # ports:
    #   - 3000:3000
    environment:
      - NODE_ENV=production
  nginx:
    container_name: ifc-proxy
    image: cesosag/ifc-proxy
    environment:
      - DOMAIN=iglesiafc.com
      - WEB_SERVICE_NAME=web
      - WEB_SERVICE_PORT=3000
    volumes:
      - nginx_logs:/var/log/nginx
      - nginx_run:/var/run
      - nginx_cache:/var/cache/nginx
      # - letsencrypt:/etc/letsencrypt
      # - certbot_:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  # certbot:
  #   container_name: ifc-certbot
  #   image: certbot/certbot
  #   volumes:
  #     - letsencrypt:/etc/letsencrypt
  #     - certbot_:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  nginx_logs:
  nginx_run:
  nginx_cache:
  # letsencrypt:
  # certbot_:
