# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - iglesiafc.com

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js version ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies 📦
        run: yarn --frozen-lockfile

      - name: Test and build
        run: yarn build

      - name: Zip artifact for deployment
        run: |
          cp -r apps/web/public apps/web/.next/standalone
          cp -r apps/web/.next/static apps/web/.next/standalone/.next
          cd apps/web/.next/standalone
          zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: apps/web/.next/standalone/release.zip

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      MICROSOFT_GRAPH_TENANT: ${{ secrets.MICROSOFT_GRAPH_TENANT }}
      MICROSOFT_GRAPH_CLIENT_ID: ${{ secrets.MICROSOFT_GRAPH_CLIENT_ID }}
      MICROSOFT_GRAPH_CLIENT_SECRET: ${{ secrets.MICROSOFT_GRAPH_CLIENT_SECRET }}
      WIX_ENDPOINT: ${{ secrets.WIX_ENDPOINT }}
      WIX_CONTACT_FORM_PATH: ${{ secrets.WIX_CONTACT_FORM_PATH }}
      RADIO_SERVER: ${{ secrets.RADIO_SERVER }}
      RADIO_SERVER_NAME: ${{ secrets.RADIO_SERVER_NAME }}
      NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'forestcitydev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D0A1EAA1086C4FB98CBD3EB561B91CA1 }}
          package: .
